/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  LocationInputType: { // input type
    latitude: string; // String!
    longitude: string; // String!
  }
  NameAmountJsonInput: { // input type
    amount: string; // String!
    name: string; // String!
  }
}

export interface NexusGenEnums {
  DirectionTypeEnum: "IN" | "OUT"
  ExpenseTypeEnum: "EXPENSE" | "INCOME"
  TransactionMethodEnum: "Debit" | "QRIS" | "VirtualAccount" | "mPayment"
  typeOfAccount: "CASH" | "DEBIT" | "EMONEY" | "EWALLET" | "PAYLATER"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayLoad: { // root type
    token: string; // String!
  }
  CashAccount: { // root type
    accountName: string; // String!
    balance: string; // String!
    createdAt: string; // String!
    currency: string; // String!
    displayPicture?: string | null; // String
    id: string; // String!
    lastUpdate: string; // String!
    userId: string; // String!
  }
  CashTransaction: { // root type
    amount: string; // String!
    cashAccountId: string; // String!
    category?: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    currency: string; // String!
    dateTimestamp: string; // String!
    direction: string; // String!
    id: string; // String!
    internalTransferTransactionId?: string | null; // String
    isHideFromBudget: boolean; // Boolean!
    isHideFromInsight: boolean; // Boolean!
    location?: NexusGenRootTypes['Location'] | null; // Location
    merchant: NexusGenRootTypes['Merchant']; // Merchant!
    merchantId: string; // String!
    notes?: string | null; // String
    tags?: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    transactionName: string; // String!
    transactionType: string; // String!
  }
  DebitAccount: { // root type
    accountNumber: string; // String!
    balance: string; // String!
    createdAt: string; // String!
    currency: string; // String!
    id: string; // String!
    institutionId: string; // String!
    lastUpdate: string; // String!
    userId: string; // String!
  }
  DebitTransaction: { // root type
    amount: string; // String!
    category?: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    currency: string; // String!
    dateTimestamp: string; // String!
    debitAccountId: string; // String!
    description: string; // String!
    direction: string; // String!
    id: string; // String!
    institutionId: string; // String!
    internalTransferTransactionId?: string | null; // String
    isHideFromBudget: boolean; // Boolean!
    isHideFromInsight: boolean; // Boolean!
    isReviewed: boolean; // Boolean!
    isSubscription: boolean; // Boolean!
    location?: NexusGenRootTypes['Location'] | null; // Location
    merchant: NexusGenRootTypes['Merchant']; // Merchant!
    merchantId: string; // String!
    notes?: string | null; // String
    onlineTransaction: boolean; // Boolean!
    referenceId: string; // String!
    tags?: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    transactionMethod: string; // String!
    transactionName: string; // String!
    transactionType: string; // String!
  }
  EMoneyAccount: { // root type
    balance: string; // String!
    cardNumber: string; // String!
    createdAt: string; // String!
    currency: string; // String!
    id: string; // String!
    institutionId: string; // String!
    lastUpdate: string; // String!
    userId: string; // String!
  }
  EMoneyTransaction: { // root type
    amount: string; // String!
    category?: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    currency: string; // String!
    dateTimestamp: string; // String!
    description?: string | null; // String
    direction: string; // String!
    eMoneyAccountId: string; // String!
    id: string; // String!
    institutionId: string; // String!
    internalTransferTransactionId?: string | null; // String
    isHideFromBudget: boolean; // Boolean!
    isHideFromInsight: boolean; // Boolean!
    isReviewed: boolean; // Boolean!
    location?: NexusGenRootTypes['Location'] | null; // Location
    merchant: NexusGenRootTypes['Merchant']; // Merchant!
    merchantId: string; // String!
    notes?: string | null; // String
    tags?: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    transactionName: string; // String!
    transactionType: string; // String!
  }
  EWalletAccount: { // root type
    accountNumber: string; // String!
    balance: string; // String!
    createdAt: string; // String!
    currency: string; // String!
    id: string; // String!
    institutionId: string; // String!
    lastUpdate: string; // String!
    userId: string; // String!
  }
  EWalletTransaction: { // root type
    amount: string; // String!
    category?: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    currency: string; // String!
    dateTimestamp: string; // String!
    description: string; // String!
    direction: string; // String!
    eWalletAccountId: string; // String!
    id: string; // String!
    institutionId: string; // String!
    internalTransferTransactionId?: string | null; // String
    isHideFromBudget: boolean; // Boolean!
    isHideFromInsight: boolean; // Boolean!
    isReviewed: boolean; // Boolean!
    isSubscription: boolean; // Boolean!
    location?: NexusGenRootTypes['Location'] | null; // Location
    merchant: NexusGenRootTypes['Merchant']; // Merchant!
    merchantId: string; // String!
    notes?: string | null; // String
    onlineTransaction: boolean; // Boolean!
    referenceId: string; // String!
    tags?: Array<NexusGenRootTypes['NameAmountJson'] | null> | null; // [NameAmountJson]
    transactionName: string; // String!
    transactionType: string; // String!
  }
  Location: { // root type
    latitude: string; // String!
    longitude: string; // String!
  }
  Merchant: { // root type
    id: string; // String!
    name: string; // String!
    picture: string; // String!
    url: string; // String!
  }
  Mutation: {};
  NameAmountJson: { // root type
    amount: string; // String!
    name: string; // String!
  }
  OTPData: { // root type
    clientId: number; // Int!
    otpToken: string; // String!
    redirectRefId: number; // Int!
    sessionId: string; // String!
    uniqueId: string; // String!
    username: string; // String!
  }
  PayLaterAccount: { // root type
    accountNumber: string; // String!
    balance: string; // String!
    createdAt: string; // String!
    currency: string; // String!
    id: string; // String!
    institutionId: string; // String!
    lastUpdate: string; // String!
    userId: string; // String!
  }
  PayLaterTransaction: { // root type
    amount: string; // String!
    category?: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    currency: string; // String!
    dateTimestamp: string; // String!
    description: string; // String!
    direction: string; // String!
    id: string; // String!
    institutionId: string; // String!
    internalTransferTransactionId?: string | null; // String
    isHideFromBudget: boolean; // Boolean!
    isHideFromInsight: boolean; // Boolean!
    isReviewed: boolean; // Boolean!
    isSubscription: boolean; // Boolean!
    location?: NexusGenRootTypes['Location'] | null; // Location
    merchant: NexusGenRootTypes['Merchant']; // Merchant!
    merchantId: string; // String!
    notes?: string | null; // String
    onlineTransaction: boolean; // Boolean!
    payLaterAccountId: string; // String!
    referenceId: string; // String!
    tags?: Array<NexusGenRootTypes['NameAmountJson'] | null> | null; // [NameAmountJson]
    transactionName: string; // String!
    transactionType: string; // String!
  }
  Profile: { // root type
    bio?: string | null; // String
    birthday?: string | null; // String
    id: string; // String!
    profilePicture?: string | null; // String
    user: NexusGenRootTypes['User']; // User!
    userId: string; // String!
  }
  Query: {};
  Refresh: { // root type
    date: string; // String!
    id: string; // String!
    user: NexusGenRootTypes['User']; // User!
    userId: string; // String!
  }
  ResponseMessage: { // root type
    response?: string | null; // String
  }
  User: { // root type
    createdAt: string; // String!
    email: string; // String!
    firstName: string; // String!
    id: string; // String!
    kudosNo: number; // Int!
    lastName: string; // String!
    username: string; // String!
    whatsapp: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AuthPayLoad: { // field return type
    token: string; // String!
  }
  CashAccount: { // field return type
    accountName: string; // String!
    balance: string; // String!
    createdAt: string; // String!
    currency: string; // String!
    displayPicture: string | null; // String
    id: string; // String!
    lastUpdate: string; // String!
    userId: string; // String!
  }
  CashTransaction: { // field return type
    amount: string; // String!
    cashAccountId: string; // String!
    category: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    currency: string; // String!
    dateTimestamp: string; // String!
    direction: string; // String!
    id: string; // String!
    internalTransferTransactionId: string | null; // String
    isHideFromBudget: boolean; // Boolean!
    isHideFromInsight: boolean; // Boolean!
    location: NexusGenRootTypes['Location'] | null; // Location
    merchant: NexusGenRootTypes['Merchant']; // Merchant!
    merchantId: string; // String!
    notes: string | null; // String
    tags: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    transactionName: string; // String!
    transactionType: string; // String!
  }
  DebitAccount: { // field return type
    accountNumber: string; // String!
    balance: string; // String!
    createdAt: string; // String!
    currency: string; // String!
    id: string; // String!
    institutionId: string; // String!
    lastUpdate: string; // String!
    userId: string; // String!
  }
  DebitTransaction: { // field return type
    amount: string; // String!
    category: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    currency: string; // String!
    dateTimestamp: string; // String!
    debitAccountId: string; // String!
    description: string; // String!
    direction: string; // String!
    id: string; // String!
    institutionId: string; // String!
    internalTransferTransactionId: string | null; // String
    isHideFromBudget: boolean; // Boolean!
    isHideFromInsight: boolean; // Boolean!
    isReviewed: boolean; // Boolean!
    isSubscription: boolean; // Boolean!
    location: NexusGenRootTypes['Location'] | null; // Location
    merchant: NexusGenRootTypes['Merchant']; // Merchant!
    merchantId: string; // String!
    notes: string | null; // String
    onlineTransaction: boolean; // Boolean!
    referenceId: string; // String!
    tags: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    transactionMethod: string; // String!
    transactionName: string; // String!
    transactionType: string; // String!
  }
  EMoneyAccount: { // field return type
    balance: string; // String!
    cardNumber: string; // String!
    createdAt: string; // String!
    currency: string; // String!
    id: string; // String!
    institutionId: string; // String!
    lastUpdate: string; // String!
    userId: string; // String!
  }
  EMoneyTransaction: { // field return type
    amount: string; // String!
    category: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    currency: string; // String!
    dateTimestamp: string; // String!
    description: string | null; // String
    direction: string; // String!
    eMoneyAccountId: string; // String!
    id: string; // String!
    institutionId: string; // String!
    internalTransferTransactionId: string | null; // String
    isHideFromBudget: boolean; // Boolean!
    isHideFromInsight: boolean; // Boolean!
    isReviewed: boolean; // Boolean!
    location: NexusGenRootTypes['Location'] | null; // Location
    merchant: NexusGenRootTypes['Merchant']; // Merchant!
    merchantId: string; // String!
    notes: string | null; // String
    tags: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    transactionName: string; // String!
    transactionType: string; // String!
  }
  EWalletAccount: { // field return type
    accountNumber: string; // String!
    balance: string; // String!
    createdAt: string; // String!
    currency: string; // String!
    id: string; // String!
    institutionId: string; // String!
    lastUpdate: string; // String!
    userId: string; // String!
  }
  EWalletTransaction: { // field return type
    amount: string; // String!
    category: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    currency: string; // String!
    dateTimestamp: string; // String!
    description: string; // String!
    direction: string; // String!
    eWalletAccountId: string; // String!
    id: string; // String!
    institutionId: string; // String!
    internalTransferTransactionId: string | null; // String
    isHideFromBudget: boolean; // Boolean!
    isHideFromInsight: boolean; // Boolean!
    isReviewed: boolean; // Boolean!
    isSubscription: boolean; // Boolean!
    location: NexusGenRootTypes['Location'] | null; // Location
    merchant: NexusGenRootTypes['Merchant']; // Merchant!
    merchantId: string; // String!
    notes: string | null; // String
    onlineTransaction: boolean; // Boolean!
    referenceId: string; // String!
    tags: Array<NexusGenRootTypes['NameAmountJson'] | null> | null; // [NameAmountJson]
    transactionName: string; // String!
    transactionType: string; // String!
  }
  Location: { // field return type
    latitude: string; // String!
    longitude: string; // String!
  }
  Merchant: { // field return type
    id: string; // String!
    name: string; // String!
    picture: string; // String!
    url: string; // String!
  }
  Mutation: { // field return type
    addCashAccount: NexusGenRootTypes['CashAccount']; // CashAccount!
    addCashTransaction: NexusGenRootTypes['CashTransaction']; // CashTransaction!
    addEMoneyTransaction: NexusGenRootTypes['EMoneyTransaction']; // EMoneyTransaction!
    addMerchant: NexusGenRootTypes['Merchant']; // Merchant!
    changePassword: NexusGenRootTypes['AuthPayLoad']; // AuthPayLoad!
    changePin: NexusGenRootTypes['AuthPayLoad']; // AuthPayLoad!
    connectBcaViaBrick: NexusGenRootTypes['DebitAccount']; // DebitAccount!
    connectGopayViaBrick: NexusGenRootTypes['EWalletAccount'][]; // [EWalletAccount!]!
    createEMoneyAccount: NexusGenRootTypes['EMoneyAccount']; // EMoneyAccount!
    deleteCashAccount: NexusGenRootTypes['ResponseMessage'] | null; // ResponseMessage
    deleteCashTransaction: NexusGenRootTypes['ResponseMessage'] | null; // ResponseMessage
    deleteDebitAccount: NexusGenRootTypes['ResponseMessage'] | null; // ResponseMessage
    deleteEMoneyAccount: NexusGenRootTypes['ResponseMessage'] | null; // ResponseMessage
    deleteEMoneyTransaction: NexusGenRootTypes['ResponseMessage']; // ResponseMessage!
    deleteGopayAccount: NexusGenRootTypes['ResponseMessage'] | null; // ResponseMessage
    editCashAccount: NexusGenRootTypes['CashAccount']; // CashAccount!
    editCashTransaction: NexusGenRootTypes['CashTransaction']; // CashTransaction!
    editDebitTransaction: NexusGenRootTypes['DebitTransaction']; // DebitTransaction!
    editEMoneyTransaction: NexusGenRootTypes['EMoneyTransaction']; // EMoneyTransaction!
    editEWalletTransaction: NexusGenRootTypes['EWalletTransaction']; // EWalletTransaction!
    editPayLaterTransaction: NexusGenRootTypes['PayLaterTransaction']; // PayLaterTransaction!
    reconcileCashBalance: NexusGenRootTypes['CashAccount']; // CashAccount!
    reconcileEMoneyAccount: NexusGenRootTypes['EMoneyAccount']; // EMoneyAccount!
    refreshBcaTransactionViaBrick: Array<NexusGenRootTypes['DebitTransaction'] | null> | null; // [DebitTransaction]
    refreshGopayTransactionViaBrick: NexusGenRootTypes['ResponseMessage']; // ResponseMessage!
    signup: NexusGenRootTypes['AuthPayLoad']; // AuthPayLoad!
    updateEmailOrWhatsapp: NexusGenRootTypes['User']; // User!
    updateProfile: NexusGenRootTypes['Profile']; // Profile!
    updateUserFirstAndLastName: NexusGenRootTypes['User']; // User!
  }
  NameAmountJson: { // field return type
    amount: string; // String!
    name: string; // String!
  }
  OTPData: { // field return type
    clientId: number; // Int!
    otpToken: string; // String!
    redirectRefId: number; // Int!
    sessionId: string; // String!
    uniqueId: string; // String!
    username: string; // String!
  }
  PayLaterAccount: { // field return type
    accountNumber: string; // String!
    balance: string; // String!
    createdAt: string; // String!
    currency: string; // String!
    id: string; // String!
    institutionId: string; // String!
    lastUpdate: string; // String!
    userId: string; // String!
  }
  PayLaterTransaction: { // field return type
    amount: string; // String!
    category: NexusGenRootTypes['NameAmountJson'][] | null; // [NameAmountJson!]
    currency: string; // String!
    dateTimestamp: string; // String!
    description: string; // String!
    direction: string; // String!
    id: string; // String!
    institutionId: string; // String!
    internalTransferTransactionId: string | null; // String
    isHideFromBudget: boolean; // Boolean!
    isHideFromInsight: boolean; // Boolean!
    isReviewed: boolean; // Boolean!
    isSubscription: boolean; // Boolean!
    location: NexusGenRootTypes['Location'] | null; // Location
    merchant: NexusGenRootTypes['Merchant']; // Merchant!
    merchantId: string; // String!
    notes: string | null; // String
    onlineTransaction: boolean; // Boolean!
    payLaterAccountId: string; // String!
    referenceId: string; // String!
    tags: Array<NexusGenRootTypes['NameAmountJson'] | null> | null; // [NameAmountJson]
    transactionName: string; // String!
    transactionType: string; // String!
  }
  Profile: { // field return type
    bio: string | null; // String
    birthday: string | null; // String
    id: string; // String!
    profilePicture: string | null; // String
    user: NexusGenRootTypes['User']; // User!
    userId: string; // String!
  }
  Query: { // field return type
    getAllCashAccount: Array<NexusGenRootTypes['CashAccount'] | null> | null; // [CashAccount]
    getAllCashTransaction: Array<NexusGenRootTypes['CashTransaction'] | null> | null; // [CashTransaction]
    getAllDebitAccount: Array<NexusGenRootTypes['DebitAccount'] | null> | null; // [DebitAccount]
    getAllDebitTransaction: Array<NexusGenRootTypes['DebitTransaction'] | null> | null; // [DebitTransaction]
    getAllEMoneyAccount: Array<NexusGenRootTypes['EMoneyAccount'] | null> | null; // [EMoneyAccount]
    getAllEMoneyTransaction: Array<NexusGenRootTypes['EMoneyTransaction'] | null> | null; // [EMoneyTransaction]
    getAllEWalletAccount: Array<NexusGenRootTypes['EWalletAccount'] | null> | null; // [EWalletAccount]
    getAllEWalletTransaction: Array<NexusGenRootTypes['EWalletTransaction'] | null> | null; // [EWalletTransaction]
    getAllMerchant: NexusGenRootTypes['Merchant'][]; // [Merchant!]!
    getAllPayLaterAccount: Array<NexusGenRootTypes['PayLaterAccount'] | null> | null; // [PayLaterAccount]
    getAllPayLaterTransaction: Array<NexusGenRootTypes['PayLaterTransaction'] | null> | null; // [PayLaterTransaction]
    getAllUser: Array<NexusGenRootTypes['User'] | null>; // [User]!
    getOtp: NexusGenRootTypes['ResponseMessage'] | null; // ResponseMessage
    getProfile: NexusGenRootTypes['Profile'] | null; // Profile
    getRefresh: Array<NexusGenRootTypes['Refresh'] | null> | null; // [Refresh]
    getUser: NexusGenRootTypes['User'] | null; // User
    login: NexusGenRootTypes['AuthPayLoad']; // AuthPayLoad!
    sendOtpGopayViaBrick: NexusGenRootTypes['OTPData'] | null; // OTPData
    verifyOtp: NexusGenRootTypes['AuthPayLoad']; // AuthPayLoad!
    verifyPin: NexusGenRootTypes['AuthPayLoad']; // AuthPayLoad!
  }
  Refresh: { // field return type
    date: string; // String!
    id: string; // String!
    user: NexusGenRootTypes['User']; // User!
    userId: string; // String!
  }
  ResponseMessage: { // field return type
    response: string | null; // String
  }
  User: { // field return type
    createdAt: string; // String!
    email: string; // String!
    firstName: string; // String!
    id: string; // String!
    kudosNo: number; // Int!
    lastName: string; // String!
    username: string; // String!
    whatsapp: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayLoad: { // field return type name
    token: 'String'
  }
  CashAccount: { // field return type name
    accountName: 'String'
    balance: 'String'
    createdAt: 'String'
    currency: 'String'
    displayPicture: 'String'
    id: 'String'
    lastUpdate: 'String'
    userId: 'String'
  }
  CashTransaction: { // field return type name
    amount: 'String'
    cashAccountId: 'String'
    category: 'NameAmountJson'
    currency: 'String'
    dateTimestamp: 'String'
    direction: 'String'
    id: 'String'
    internalTransferTransactionId: 'String'
    isHideFromBudget: 'Boolean'
    isHideFromInsight: 'Boolean'
    location: 'Location'
    merchant: 'Merchant'
    merchantId: 'String'
    notes: 'String'
    tags: 'NameAmountJson'
    transactionName: 'String'
    transactionType: 'String'
  }
  DebitAccount: { // field return type name
    accountNumber: 'String'
    balance: 'String'
    createdAt: 'String'
    currency: 'String'
    id: 'String'
    institutionId: 'String'
    lastUpdate: 'String'
    userId: 'String'
  }
  DebitTransaction: { // field return type name
    amount: 'String'
    category: 'NameAmountJson'
    currency: 'String'
    dateTimestamp: 'String'
    debitAccountId: 'String'
    description: 'String'
    direction: 'String'
    id: 'String'
    institutionId: 'String'
    internalTransferTransactionId: 'String'
    isHideFromBudget: 'Boolean'
    isHideFromInsight: 'Boolean'
    isReviewed: 'Boolean'
    isSubscription: 'Boolean'
    location: 'Location'
    merchant: 'Merchant'
    merchantId: 'String'
    notes: 'String'
    onlineTransaction: 'Boolean'
    referenceId: 'String'
    tags: 'NameAmountJson'
    transactionMethod: 'String'
    transactionName: 'String'
    transactionType: 'String'
  }
  EMoneyAccount: { // field return type name
    balance: 'String'
    cardNumber: 'String'
    createdAt: 'String'
    currency: 'String'
    id: 'String'
    institutionId: 'String'
    lastUpdate: 'String'
    userId: 'String'
  }
  EMoneyTransaction: { // field return type name
    amount: 'String'
    category: 'NameAmountJson'
    currency: 'String'
    dateTimestamp: 'String'
    description: 'String'
    direction: 'String'
    eMoneyAccountId: 'String'
    id: 'String'
    institutionId: 'String'
    internalTransferTransactionId: 'String'
    isHideFromBudget: 'Boolean'
    isHideFromInsight: 'Boolean'
    isReviewed: 'Boolean'
    location: 'Location'
    merchant: 'Merchant'
    merchantId: 'String'
    notes: 'String'
    tags: 'NameAmountJson'
    transactionName: 'String'
    transactionType: 'String'
  }
  EWalletAccount: { // field return type name
    accountNumber: 'String'
    balance: 'String'
    createdAt: 'String'
    currency: 'String'
    id: 'String'
    institutionId: 'String'
    lastUpdate: 'String'
    userId: 'String'
  }
  EWalletTransaction: { // field return type name
    amount: 'String'
    category: 'NameAmountJson'
    currency: 'String'
    dateTimestamp: 'String'
    description: 'String'
    direction: 'String'
    eWalletAccountId: 'String'
    id: 'String'
    institutionId: 'String'
    internalTransferTransactionId: 'String'
    isHideFromBudget: 'Boolean'
    isHideFromInsight: 'Boolean'
    isReviewed: 'Boolean'
    isSubscription: 'Boolean'
    location: 'Location'
    merchant: 'Merchant'
    merchantId: 'String'
    notes: 'String'
    onlineTransaction: 'Boolean'
    referenceId: 'String'
    tags: 'NameAmountJson'
    transactionName: 'String'
    transactionType: 'String'
  }
  Location: { // field return type name
    latitude: 'String'
    longitude: 'String'
  }
  Merchant: { // field return type name
    id: 'String'
    name: 'String'
    picture: 'String'
    url: 'String'
  }
  Mutation: { // field return type name
    addCashAccount: 'CashAccount'
    addCashTransaction: 'CashTransaction'
    addEMoneyTransaction: 'EMoneyTransaction'
    addMerchant: 'Merchant'
    changePassword: 'AuthPayLoad'
    changePin: 'AuthPayLoad'
    connectBcaViaBrick: 'DebitAccount'
    connectGopayViaBrick: 'EWalletAccount'
    createEMoneyAccount: 'EMoneyAccount'
    deleteCashAccount: 'ResponseMessage'
    deleteCashTransaction: 'ResponseMessage'
    deleteDebitAccount: 'ResponseMessage'
    deleteEMoneyAccount: 'ResponseMessage'
    deleteEMoneyTransaction: 'ResponseMessage'
    deleteGopayAccount: 'ResponseMessage'
    editCashAccount: 'CashAccount'
    editCashTransaction: 'CashTransaction'
    editDebitTransaction: 'DebitTransaction'
    editEMoneyTransaction: 'EMoneyTransaction'
    editEWalletTransaction: 'EWalletTransaction'
    editPayLaterTransaction: 'PayLaterTransaction'
    reconcileCashBalance: 'CashAccount'
    reconcileEMoneyAccount: 'EMoneyAccount'
    refreshBcaTransactionViaBrick: 'DebitTransaction'
    refreshGopayTransactionViaBrick: 'ResponseMessage'
    signup: 'AuthPayLoad'
    updateEmailOrWhatsapp: 'User'
    updateProfile: 'Profile'
    updateUserFirstAndLastName: 'User'
  }
  NameAmountJson: { // field return type name
    amount: 'String'
    name: 'String'
  }
  OTPData: { // field return type name
    clientId: 'Int'
    otpToken: 'String'
    redirectRefId: 'Int'
    sessionId: 'String'
    uniqueId: 'String'
    username: 'String'
  }
  PayLaterAccount: { // field return type name
    accountNumber: 'String'
    balance: 'String'
    createdAt: 'String'
    currency: 'String'
    id: 'String'
    institutionId: 'String'
    lastUpdate: 'String'
    userId: 'String'
  }
  PayLaterTransaction: { // field return type name
    amount: 'String'
    category: 'NameAmountJson'
    currency: 'String'
    dateTimestamp: 'String'
    description: 'String'
    direction: 'String'
    id: 'String'
    institutionId: 'String'
    internalTransferTransactionId: 'String'
    isHideFromBudget: 'Boolean'
    isHideFromInsight: 'Boolean'
    isReviewed: 'Boolean'
    isSubscription: 'Boolean'
    location: 'Location'
    merchant: 'Merchant'
    merchantId: 'String'
    notes: 'String'
    onlineTransaction: 'Boolean'
    payLaterAccountId: 'String'
    referenceId: 'String'
    tags: 'NameAmountJson'
    transactionName: 'String'
    transactionType: 'String'
  }
  Profile: { // field return type name
    bio: 'String'
    birthday: 'String'
    id: 'String'
    profilePicture: 'String'
    user: 'User'
    userId: 'String'
  }
  Query: { // field return type name
    getAllCashAccount: 'CashAccount'
    getAllCashTransaction: 'CashTransaction'
    getAllDebitAccount: 'DebitAccount'
    getAllDebitTransaction: 'DebitTransaction'
    getAllEMoneyAccount: 'EMoneyAccount'
    getAllEMoneyTransaction: 'EMoneyTransaction'
    getAllEWalletAccount: 'EWalletAccount'
    getAllEWalletTransaction: 'EWalletTransaction'
    getAllMerchant: 'Merchant'
    getAllPayLaterAccount: 'PayLaterAccount'
    getAllPayLaterTransaction: 'PayLaterTransaction'
    getAllUser: 'User'
    getOtp: 'ResponseMessage'
    getProfile: 'Profile'
    getRefresh: 'Refresh'
    getUser: 'User'
    login: 'AuthPayLoad'
    sendOtpGopayViaBrick: 'OTPData'
    verifyOtp: 'AuthPayLoad'
    verifyPin: 'AuthPayLoad'
  }
  Refresh: { // field return type name
    date: 'String'
    id: 'String'
    user: 'User'
    userId: 'String'
  }
  ResponseMessage: { // field return type name
    response: 'String'
  }
  User: { // field return type name
    createdAt: 'String'
    email: 'String'
    firstName: 'String'
    id: 'String'
    kudosNo: 'Int'
    lastName: 'String'
    username: 'String'
    whatsapp: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addCashAccount: { // args
      accountName: string; // String!
      currency: string; // String!
      displayPicture?: string | null; // String
      startingBalance: string; // String!
    }
    addCashTransaction: { // args
      amount: string; // String!
      cashAccountId: string; // String!
      category: Array<NexusGenInputs['NameAmountJsonInput'] | null>; // [NameAmountJsonInput]!
      currency: string; // String!
      direction: NexusGenEnums['DirectionTypeEnum']; // DirectionTypeEnum!
      isHideFromBudget: boolean; // Boolean!
      isHideFromInsight: boolean; // Boolean!
      location?: NexusGenInputs['LocationInputType'] | null; // LocationInputType
      merchantId: string; // String!
      notes?: string | null; // String
      tags?: Array<NexusGenInputs['NameAmountJsonInput'] | null> | null; // [NameAmountJsonInput]
      transactionName: string; // String!
      transactionType: NexusGenEnums['ExpenseTypeEnum']; // ExpenseTypeEnum!
    }
    addEMoneyTransaction: { // args
      amount: string; // String!
      category: Array<NexusGenInputs['NameAmountJsonInput'] | null>; // [NameAmountJsonInput]!
      currency: string; // String!
      description?: string | null; // String
      direction: NexusGenEnums['DirectionTypeEnum']; // DirectionTypeEnum!
      eMoneyAccountId: string; // String!
      institutionId: string; // String!
      isHideFromBudget: boolean; // Boolean!
      isHideFromInsight: boolean; // Boolean!
      location?: NexusGenInputs['LocationInputType'] | null; // LocationInputType
      merchantId: string; // String!
      notes?: string | null; // String
      tags?: Array<NexusGenInputs['NameAmountJsonInput'] | null> | null; // [NameAmountJsonInput]
      transactionName: string; // String!
      transactionType: string; // String!
    }
    addMerchant: { // args
      name: string; // String!
      picture: string; // String!
      url: string; // String!
    }
    changePassword: { // args
      jwtToken: string; // String!
      password: string; // String!
    }
    changePin: { // args
      jwtToken: string; // String!
      pin: string; // String!
    }
    connectBcaViaBrick: { // args
      brickInstitutionId: number; // Int!
      password: string; // String!
      username: string; // String!
    }
    connectGopayViaBrick: { // args
      clientId: number; // Int!
      otp: string; // String!
      otpToken: string; // String!
      redirectRefId: number; // Int!
      sessionId: string; // String!
      uniqueId: string; // String!
      username: string; // String!
    }
    createEMoneyAccount: { // args
      cardNumber: string; // String!
      currency: string; // String!
      initialBalance: string; // String!
      institutionId: string; // String!
    }
    deleteCashAccount: { // args
      cashAccountId: string; // String!
    }
    deleteCashTransaction: { // args
      transactionId: string; // String!
    }
    deleteDebitAccount: { // args
      debitAccountId: string; // String!
    }
    deleteEMoneyAccount: { // args
      eMoneyAccountId: string; // String!
    }
    deleteEMoneyTransaction: { // args
      transactionId: string; // String!
    }
    deleteGopayAccount: { // args
      eWalletAccountId: string; // String!
    }
    editCashAccount: { // args
      accountName: string | null; // String
      cashAccountId: string; // String!
      displayPicture?: string | null; // String
    }
    editCashTransaction: { // args
      amount?: string | null; // String
      category?: Array<NexusGenInputs['NameAmountJsonInput'] | null> | null; // [NameAmountJsonInput]
      currency: string | null; // String
      direction?: NexusGenEnums['DirectionTypeEnum'] | null; // DirectionTypeEnum
      isHideFromBudget?: boolean | null; // Boolean
      isHideFromInsight?: boolean | null; // Boolean
      location?: NexusGenInputs['LocationInputType'] | null; // LocationInputType
      merchantId?: string | null; // String
      notes?: string | null; // String
      tags?: Array<NexusGenInputs['NameAmountJsonInput'] | null> | null; // [NameAmountJsonInput]
      transactionId: string; // String!
      transactionName?: string | null; // String
      transactionType?: NexusGenEnums['ExpenseTypeEnum'] | null; // ExpenseTypeEnum
    }
    editDebitTransaction: { // args
      category?: Array<NexusGenInputs['NameAmountJsonInput'] | null> | null; // [NameAmountJsonInput]
      isHideFromBudget: boolean; // Boolean!
      isHideFromInsight: boolean; // Boolean!
      isSubscription?: boolean | null; // Boolean
      location?: NexusGenInputs['LocationInputType'] | null; // LocationInputType
      merchantId?: string | null; // String
      notes?: string | null; // String
      onlineTransaction?: boolean | null; // Boolean
      tags?: Array<NexusGenInputs['NameAmountJsonInput'] | null> | null; // [NameAmountJsonInput]
      transactionId: string; // String!
      transactionMethod?: NexusGenEnums['TransactionMethodEnum'] | null; // TransactionMethodEnum
      transactionName?: string | null; // String
      transactionType?: NexusGenEnums['ExpenseTypeEnum'] | null; // ExpenseTypeEnum
    }
    editEMoneyTransaction: { // args
      amount?: string | null; // String
      category?: Array<NexusGenInputs['NameAmountJsonInput'] | null> | null; // [NameAmountJsonInput]
      direction?: NexusGenEnums['DirectionTypeEnum'] | null; // DirectionTypeEnum
      isHideFromBudget?: boolean | null; // Boolean
      isHideFromInsight?: boolean | null; // Boolean
      location?: NexusGenInputs['LocationInputType'] | null; // LocationInputType
      merchantId?: string | null; // String
      notes?: string | null; // String
      tags?: Array<NexusGenInputs['NameAmountJsonInput'] | null> | null; // [NameAmountJsonInput]
      transactionId: string; // String!
      transactionName?: string | null; // String
      transactionType?: NexusGenEnums['ExpenseTypeEnum'] | null; // ExpenseTypeEnum
    }
    editEWalletTransaction: { // args
      category?: Array<NexusGenInputs['NameAmountJsonInput'] | null> | null; // [NameAmountJsonInput]
      isHideFromBudget: boolean; // Boolean!
      isHideFromInsight: boolean; // Boolean!
      isSubscription?: boolean | null; // Boolean
      location?: NexusGenInputs['LocationInputType'] | null; // LocationInputType
      merchantId?: string | null; // String
      notes?: string | null; // String
      onlineTransaction?: boolean | null; // Boolean
      tags?: Array<NexusGenInputs['NameAmountJsonInput'] | null> | null; // [NameAmountJsonInput]
      transactionId: string; // String!
      transactionName?: string | null; // String
      transactionType?: NexusGenEnums['ExpenseTypeEnum'] | null; // ExpenseTypeEnum
    }
    editPayLaterTransaction: { // args
      category?: Array<NexusGenInputs['NameAmountJsonInput'] | null> | null; // [NameAmountJsonInput]
      isHideFromBudget: boolean; // Boolean!
      isHideFromInsight: boolean; // Boolean!
      isSubscription?: boolean | null; // Boolean
      location?: NexusGenInputs['LocationInputType'] | null; // LocationInputType
      merchantId?: string | null; // String
      notes?: string | null; // String
      onlineTransaction?: boolean | null; // Boolean
      tags?: Array<NexusGenInputs['NameAmountJsonInput'] | null> | null; // [NameAmountJsonInput]
      transactionId: string; // String!
      transactionName?: string | null; // String
      transactionType?: NexusGenEnums['ExpenseTypeEnum'] | null; // ExpenseTypeEnum
    }
    reconcileCashBalance: { // args
      cashAccountId: string; // String!
      newBalance: string; // String!
    }
    reconcileEMoneyAccount: { // args
      eMoneyAccountId: string; // String!
      newBalance: string; // String!
    }
    refreshBcaTransactionViaBrick: { // args
      debitAccountId: string; // String!
    }
    refreshGopayTransactionViaBrick: { // args
      eWalletAccountId?: string | null; // String
      payLaterAccountId?: string | null; // String
    }
    signup: { // args
      id: string; // ID!
      jwtToken: string; // String!
      password: string; // String!
      pin: string; // String!
      username: string; // String!
    }
    updateEmailOrWhatsapp: { // args
      email?: string | null; // String
      jwtToken: string; // String!
      whatsapp?: string | null; // String
    }
    updateProfile: { // args
      bio?: string | null; // String
      birthday?: string | null; // String
      profilePicture?: string | null; // String
    }
    updateUserFirstAndLastName: { // args
      firstName?: string | null; // String
      lastName?: string | null; // String
    }
  }
  Query: {
    getAllCashTransaction: { // args
      cashAccountId: string; // String!
    }
    getAllDebitTransaction: { // args
      debitAccountId: string; // String!
    }
    getAllEMoneyTransaction: { // args
      eMoneyAccountId: string; // String!
    }
    getAllEWalletTransaction: { // args
      eWalletAccountId: string; // String!
    }
    getAllPayLaterTransaction: { // args
      payLaterAccountId: string; // String!
    }
    getOtp: { // args
      email?: string | null; // String
      whatsapp?: string | null; // String
    }
    getProfile: { // args
      userId?: string | null; // String
      username?: string | null; // String
    }
    getRefresh: { // args
      userId?: string | null; // String
      username?: string | null; // String
    }
    getUser: { // args
      username: string; // String!
    }
    login: { // args
      password: string; // String!
      username: string; // String!
    }
    sendOtpGopayViaBrick: { // args
      nomorHp: string; // String!
    }
    verifyOtp: { // args
      email?: string | null; // String
      otp: string; // String!
      whatsapp?: string | null; // String
    }
    verifyPin: { // args
      pin: string; // String!
      username: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}