import { objectType } from 'nexus';

export const Merchant = objectType({
  name: 'Merchant',

  definition(t) {
    t.nonNull.string('id', {
      description: 'The id automatically generated by mongoDB',
    });

    t.nonNull.string('name', {
      description: 'The name of the merchant',
    });

    t.nonNull.string('picture', {
      description: 'The display picture of that merchant',
    });
  },
});
